name: 'Ratchet'
description: 'Ensure your code metrics only improve over time'
author: 'Tiernacity'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  metric:
    description: 'Command to run that outputs a number'
    required: true
  pre:
    description: 'Command to run before metric command'
    required: false
  post:
    description: 'Command to run after metric command'
    required: false
  lt:
    description: 'Base ref for less-than comparison'
    required: false
  le:
    description: 'Base ref for less-equal comparison'
    required: false
  eq:
    description: 'Base ref for equal-to comparison'
    required: false
  ge:
    description: 'Base ref for greater-equal comparison'
    required: false
  gt:
    description: 'Base ref for greater-than comparison'
    required: false
  verbose:
    description: 'Show detailed output'
    required: false
    default: 'false'
  version:
    description: 'Version of ratchet to use (e.g., v1.0.0)'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Determine version
      id: version
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION=$(curl -s https://api.github.com/repos/tiernacity/ratchet/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        else
          VERSION="${{ inputs.version }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Download ratchet
      shell: bash
      run: |
        # Determine OS and architecture
        OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        
        # Map architecture names
        case $ARCH in
          x86_64)
            ARCH="amd64"
            ;;
          aarch64|arm64)
            ARCH="arm64"
            ;;
        esac
        
        # Set binary name
        BINARY_NAME="ratchet-${OS}-${ARCH}"
        if [[ "$OS" == "windows" ]]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi
        
        # Download binary
        URL="https://github.com/tiernacity/ratchet/releases/download/${{ steps.version.outputs.version }}/${BINARY_NAME}"
        echo "Downloading ratchet from $URL"
        curl -LO "$URL"
        
        # Make executable
        chmod +x "${BINARY_NAME}"
        
        # Move to standard location
        mkdir -p "$HOME/.local/bin"
        mv "${BINARY_NAME}" "$HOME/.local/bin/ratchet"
        
        # Add to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Run ratchet
      shell: bash
      run: |
        # Convert inputs to JSON and pass to ratchet
        ratchet --config '${{ toJSON(inputs) }}'