name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  GO_VERSION: ''

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Read Go version
      run: |
        source .github/workflows/go-version.env
        echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        CURRENT_TAG=${GITHUB_REF#refs/tags/}
        
        if [ -z "$PREV_TAG" ]; then
          echo "CHANGELOG=Initial release" >> $GITHUB_OUTPUT
        else
          CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..$CURRENT_TAG)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
    
    - name: Build binaries
      run: |
        # Create output directory
        mkdir -p dist
        
        # Build for different platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/ratchet-linux-amd64 ./cmd/ratchet
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/ratchet-linux-arm64 ./cmd/ratchet
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/ratchet-darwin-amd64 ./cmd/ratchet
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/ratchet-darwin-arm64 ./cmd/ratchet
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/ratchet-windows-amd64.exe ./cmd/ratchet
        
        # Create checksums
        cd dist
        sha256sum * > checksums.txt
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          ### macOS/Linux
          ```bash
          # Download the binary for your platform
          curl -LO https://github.com/tiernacity/ratchet/releases/download/${{ github.ref_name }}/ratchet-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed 's/x86_64/amd64/')
          
          # Make it executable
          chmod +x ratchet-*
          
          # Move to PATH (optional)
          sudo mv ratchet-* /usr/local/bin/ratchet
          ```
          
          ### Windows
          Download `ratchet-windows-amd64.exe` from the assets below.
          
          ### Verify checksums
          ```bash
          curl -LO https://github.com/tiernacity/ratchet/releases/download/${{ github.ref_name }}/checksums.txt
          sha256sum -c checksums.txt
          ```
        files: |
          dist/*
        draft: false
        prerelease: false
        generate_release_notes: true